# Generated by Django 3.2.8 on 2021-11-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('package_id', models.TextField(unique=True)),
                ('version', models.TextField()),
                ('filePath', models.TextField()),
                ('isSecret', models.BooleanField(default=False)),
                ('githubUrl', models.TextField(default='')),
                ('jsProgram', models.TextField(default='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniquePackage'),
        ),
    ]
