# Generated by Django 3.2.8 on 2021-11-12 01:38

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('packageId', models.TextField(unique=True)),
                ('filePath', models.TextField()),
                ('isSecret', models.BooleanField(default=False)),
                ('githubUrl', models.TextField(default='')),
                ('version', models.TextField(default='')),
                ('jsProgram', models.TextField(default='')),
            ],
            bases=(models.Model, registry.models.BaseModel),
        ),
    ]
