# Generated by Django 3.2.8 on 2021-11-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.TextField(),
        ),
    ]
