# Generated by Django 3.2.8 on 2021-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='githubUrl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='isSecret',
            field=models.BooleanField(default=False),
        ),
    ]
