# Generated by Django 3.2.8 on 2021-11-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='filePath',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='githubUrl',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='isSecret',
            new_name='is_secret',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='jsProgram',
            new_name='js_program',
        ),
    ]
