# Generated by Django 3.2.8 on 2021-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_package_packageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('name', 'packageId', 'version'), name='uniquePackage'),
        ),
    ]
