# Generated by Django 3.2.8 on 2021-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20211112_1358'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='package',
            name='uniquePackage',
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniquePackage'),
        ),
    ]
