#! /usr/bin/bash
if [ "$1" == "install" ]; then
  python3 -m venv env/
  source env/bin/activate
  pip3 install --upgrade pip
  python -m pip install requests
  pip freeze > requirements.txt
  pip install -r requirements.txt
  deactivate
fi

if [ "$1" != "install" ]; then
  python3 -m venv env/
  source env/bin/activate
  pip3 install --upgrade pip
  #python -m pip install requests
  pip freeze > requirements.txt
  #pip install -r requirements.txt
  python3 main.py "$1"
  deactivate
fi
