name: Deploy to GAE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: update app.yaml
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.home }}/project2/app.yaml
        contents: |
          env_variables:
            TOKEN: "${{ secrets.TOKEN }}"
        write-mode: append

    - name: deploy to app engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: project2/app.yaml
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}
