name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip
    - name: Analysing the code with django-pylint
      run: |
        cd project2/
        pylint --load-plugins pylint_django --django-settings-module=project2.settings --disable=missing-module-docstring,missing-function-docstring,broad-except,missing-class-docstring,unused-wildcard-import,wildcard-import registry
