name: test_on_pull
on: [push]
jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: set up runner
        uses: actions/checkout@v2
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          ./run install
